routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use \App\Http\Controllers\PostController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\GalleryController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/cgu', function () {
    return view('/cgu');
});


// Route Main
Route::get('index', [HomeController::class, 'home'])->name('index');

// Routes Posts
Route::resource('posts', PostController::class);

// Routes Médias
Route::resource('medias', MediaController::class);

// Route Contact
Route::post('contact', [ContactController::class, 'store'])->name('contact');

// Route Commentaires
Route::post('comments', [CommentController::class, 'store'])->name('comments.store');
Route::delete('comments/{id}', [CommentController::class, 'destroy'])->name('comments.delete');

// Route::get('/test-contact', function () {
//     return new App\Mail\ContactMail([
//       'name' => 'Durand',
//       'email' => 'durand@chezlui.com',
//       'message' => 'Je voulais vous dire que votre site est magnifique !'
//       ]);
// });

// Routes Mails
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');


// Routes Auth
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('profile.show');
})->name('dashboard');

// Route Admin
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    Route::get('/admin')->middleware('admin');

// Routes Galerie Photos
    Route::post('/image-store', [GalleryController::class, 'store'])->name('image-store');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory;

    protected $dates = ['deleted_at'];

    protected $table = 'posts';

    protected $fillable = [
        'title',
        'message',
        'image'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class PostController extends Controller
{

    public function __construct() {

        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){

        // $posts = Post::orderBy('created_at', 'desc')->simplePaginate(5);
        // return view('index', ['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        //
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){

        $this->validate($request, [

        // Validation des conditions requises des champs du formulaire
            'title' => 'required|string|min:5|max:50',
            'message' => 'required|string|min:10|max:1000',
            'image' => 'required|mimes:bmp,png,jpg,jpeg|max:2048'
        ]);

        $post = new Post;
        $post->title = $request->input('title');
        $post->message = $request->input('message');
        $post->image = $request->file('image');
        $imageName = time() . $post->image->getClientOriginalName();
        $post->image->move('uploads/posts', $imageName);
        $post->image = $imageName;
        $post->user_id = Auth::user()->id;
        $post->save();

        return redirect('index')->with('success', 'Votre article à été crée !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id){

        $post = Post::with('user')->find($id);
        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id){

        $post = Post::find($id);

    if(auth()->user()->id !== $post->user_id) {

        return redirect('/posts')->with('error', 'Non autorisé');
        }
        return view('posts.edit')->with('post', $post);
        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){

        $this->validate($request, [

        // Validation des conditions requises des champs du formulaire
            'title' => 'required|string|min:5|max:50',
            'message' => 'required|string|min:10|max:1000',
            'image' => 'required|mimes:bmp,png,jpg,jpeg|max:2048'
        ]);

        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->message = $request->input('message');
        $post->image = $request->file('image');
        $imageName = time() . $post->image->getClientOriginalName();
        $post->image->move('uploads/posts', $imageName);
        $post->image = $imageName;
        $post->user_id = Auth::user()->id;
        $post->save();

        return back()->with('success', 'Votre article à été modifié !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {

        $post = Post::find($id);

        if(auth()->user()->id !== $post->user_id) {
            return redirect('posts.show')->with('error', 'Non autorisé');
        }

        $post->delete();

        return redirect('/index#home')->with('success', 'Votre article à bien été supprimé !');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/posts/commentsDisplay.blade.php
@foreach($comments as $comment)
<div class="display-comment" id="comments" @if($comment->parent_id != null) style="margin-left:35px; margin-top:-25px" @endif>

    <div class="media p-3">
        <img src="{{ $comment->user->profile_photo_url }}" alt="{{ $comment->user->name }}" class="mr-3 mt-3 rounded-circle" style="width:40px;">
        <div class="media-body">
          <h6><strong class="username">{{ $comment->user->name }}</strong>&nbsp;&nbsp;<small><i>{{ $comment->created_at->diffForHumans() }}</i></small></h6>

    <div class="options">
        <div class="optionreply">
            <p class="commentaire">{{ $comment->message }}</p>
            @auth
            <a href="" id="reply" class="ml-4 reply" data-bs-toggle="collapse" data-bs-target="#collapse{{ $comment->id }}">
                <i class="far fa-comments"></i>&nbsp;Répondre</a>
            @endauth
        </div>
        <div class="optiondelete">
            {{-- Si l'auth est l'auteur du commentaire, alors il peut le supprimer --}}
            @if (auth()->user() == ($comment->user))
            <form method="POST" action="{{ route('comments.delete', $comment->id )}}"
                onclick=" return confirm('Êtes-vous sur de vouloir supprimer ce commentaire ?')">
                @method('DELETE')
                @csrf
                <button class="ml-4"><i class="far fa-times-circle"></i></button>
            </form>
            @endif
        </div>
    </div>
    </div>
</div>
    <form method="POST" action="{{ route('comments.store') }}">
        @csrf
        <div class="form-group collapse" id="collapse{{ $comment->id }}">
            <x-jet-input type="text" name="message" class="form-control" placeholder="Écrire un commentaire..." />
            <x-jet-input type="hidden" name="post_id" value="{{ $post_id }}" />
            <x-jet-input type="hidden" name="parent_id" value="{{ $comment->id }}" />
        </div>
        {{-- <div class="form-group">
                <x-jet-button class="ml-4">
                    <i class="far fa-comments"></i>&nbsp;
                    {{ __('Répondre') }}
        </x-jet-button>
         </div> --}}
    </form>

@include('posts.commentsDisplay', ['comments' => $comment->replies])

</div>
@endforeach

resources/views/posts/create.blade.php
<x-app-layout>
    <div class="tm-main">
        <div class="tm-section-wrap">
            <div class="tm-parallax" data-parallax="scroll" data-image-src="{{ asset('img/slide4.jpg') }}">
            </div>
            <section id="home" class="tm-section">
                <h2 class="tm-text-primary">Création d'un article</h2>
                <hr class="mb-5">
                <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="mt-4">
                        <x-jet-label for="title" value="{{ __('Titre') }}" />
                        <x-jet-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')"
                            placeholder="Titre" required autofocus />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="message" value="{{ __('Message') }}" />
                        <textarea id="message" class="block mt-1 w-full" type="text" name="message" cols="30" rows="10"
                            required placeholder="Contenu de l'article"></textarea>
                    </div>

                    <div class="mt-4">
                        <div class="custom-file">
                            <label for="validatedCustomFile" class="custom-file-label">Choisir une image</label>

                            <input type="file" class="custom-file-input @error('message') is-invalid @enderror"
                                name="image" id="validatedCustomFile">
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <a class="underline text-sm text-gray-600 hover:text-gray-900" href="/index">
                            {{ __('Annuler') }}
                        </a>

                        <x-jet-button class="ml-4">
                            {{ __('Poster') }}
                        </x-jet-button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
    <div class="tm-main">
        <div class="tm-section-wrap">
            <div class="tm-parallax" data-parallax="scroll" data-image-src="{{ asset('img/slide4.jpg') }}">
            </div>
            <section id="home" class="tm-section">
                <h2 class="tm-text-primary">Modification d'un article</h2>
                <hr class="mb-5">
                <form method="POST" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mt-4">
                        <x-jet-label for="title" value="{{ __('Titre') }}" />
                        <x-jet-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')"
                            placeholder="Titre" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="message" value="{{ __('Message') }}" />
                        <textarea id="message" class="block mt-1 w-full" type="text" name="message" cols="30" rows="10"
                            required placeholder="Contenu de l'article"></textarea>
                    </div>

                    <div class="mt-4">
                        <div class="custom-file">
                            <label for="validatedCustomFile" class="custom-file-label">Choisir une image</label>

                            <input type="file" class="custom-file-input @error('message') is-invalid @enderror"
                                name="image" id="validatedCustomFile">
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <a class="underline text-sm text-gray-600 hover:text-gray-900" href="/index">
                            {{ __('Annuler') }}
                        </a>

                        <x-jet-button class="ml-4">
                            {{ __('Modifier') }}
                        </x-jet-button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
</x-app-layout>

resources/views/posts/show.blade.php
<x-guest-layout>
    <div class="tm-main">
        <div class="tm-section-wrap">
            <div class="tm-parallax" data-parallax="scroll" data-image-src="{{ asset('img/slide1.jpg') }}"></div>
            <section id="home" class="tm-section">

                <div id="section" class="box">
                    <div id="content articles box">
                                <h2 class="tm-text-primary" id="top">{{ $post->title }}</h2>
                                <div class="article-info box">
                                    <p class="f-right"><a href="#comments" class="comment"><i class="far fa-comments"></i>&nbsp;Commentaires ({{ $post->comments()->count() }})</a></p>
                                    <p class="f-left">{{ $post->created_at->format('d/m/Y') }} | Posté par <a
                                            href="#"><b class="username">{{ $post->user->name }}</b></a> | {{ $post->user->role->display_name }}</p>
                                </div>
                                <hr class="mb-5">
                    <div>
                        <img src="{{ URL::to('/uploads/posts/'.$post->image) }}" class="d-block w-100" alt="{{ $post->name }}">
                    </div>
                    <br /><br />
                                <p>{{ $post->message }}</p>
                                <br />
                                <p><a href="{{ URL::to('/uploads/posts/'.$post->image2) }}"><img src="{{ URL::to('/uploads/posts/'.$post->image2) }}" style="width: 50%" alt=""
                                        class="f-left" /></a>{{ $post->message2 }}.</p>
                                <p class="more"><a href="/index" class="btn btn-light">Retour à l'accueil</a></p>
                    </div>
               </div>
                    @auth
                    @if(Auth::user()->id == $post->user_id)
                    <hr />
                    <div class="optionsadmin">
                        <div class="optionadminedit">
                            <!-- {{-- Si l'utilisateur n'est pas l'auteur du post alors il ne peut pas l'éditer --}}-->
                            <p class="more"><a href="/posts/{{ $post->id }}/edit" class="btn btn-light">Éditer l'article</a></p>
                        </div>
                        <div class="optionadmindelete">
                            <form action="{{ route('posts.destroy', $post->id) }}" method="POST"
                                onclick=" return confirm('Êtes-vous sur de vouloir supprimer cet article ?')">
                                @csrf
                                @method('DELETE')
                                <x-jet-button class="ml-4">Supprimer</x-jet-button>
                            </form>
                        </div>
                    </div>
                    @endif
                    @endauth

                <div class="comments">
                    <hr />
                    <h5 class="tm-text-primary"><i class="far fa-comment"></i>&nbsp;Commenter</h5>
                    <hr />
                    @guest
                    <p class="text-center">Si vous voulez poster un commentaire, veuillez vous connecter ou vous
                        inscrire, <a href="/login"><b>ici</b><a>
                                <hr class="tm-hr-short mb-5">
                                @endguest
                                @auth
                                <form method="POST" action="{{ route('comments.store') }}">
                                    @csrf
                                    <div class="form-group">
                                        <x-jet-input type="text" name="message" class="form-control"
                                            placeholder="Écrire un commentaire..." />
                                        <x-jet-input type="hidden" name="post_id" value="{{ $post->id }}" />
                                    </div>

                                    <!--<div class="form-group">-->
                                    <!--<x-jet-button class="ml-4">-->
                                    <!--<i class="far fa-comment"></i>&nbsp;-->
                                    <!--{{ __('Ajouter Commentaire') }}-->
                                    <!--</x-jet-button>-->
                                    <!--</div>-->
                                </form>
                                @endauth

                                @include('posts.commentsDisplay', ['comments' => $post->comments, 'post_id' =>
                                $post->id])
                                <hr />
                                <p class="text-center more"><a href="#top"><b>Retour à l'article</b></a></p>
                </div>
            </div>
        </section>
    </div>
</div>
</x-guest-layout>