routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use \App\Http\Controllers\PostController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\GalleryController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/cgu', function () {
    return view('/cgu');
});


// Route Main
Route::get('index', [HomeController::class, 'home'])->name('index');

// Routes Posts
Route::resource('posts', PostController::class);

// Routes Médias
Route::resource('medias', MediaController::class);

// Route Contact
Route::post('contact', [ContactController::class, 'store'])->name('contact');

// Route Commentaires
Route::post('comments', [CommentController::class, 'store'])->name('comments.store');
Route::delete('comments/{id}', [CommentController::class, 'destroy'])->name('comments.delete');

// Route::get('/test-contact', function () {
//     return new App\Mail\ContactMail([
//       'name' => 'Durand',
//       'email' => 'durand@chezlui.com',
//       'message' => 'Je voulais vous dire que votre site est magnifique !'
//       ]);
// });

// Routes Mails
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');


// Routes Auth
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('profile.show');
})->name('dashboard');

// Route Admin
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    Route::get('/admin')->middleware('admin');

// Routes Galerie Photos
    Route::post('/image-store', [GalleryController::class, 'store'])->name('image-store');
});

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    use HasFactory;

    protected $dates = ['deleted_at'];

    protected $table = 'medias';

    protected $fillable = [
        'title',
        'title2',
        'link',
        'image'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/MediaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Media;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class MediaController extends Controller
{

    public function __construct() {

        $this->middleware('auth', ['except' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){

        // $medias = Media::orderBy('created_at', 'desc')->get();
        // return view('index#media', ['medias' => $medias]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        //
        return view('medias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){

        $this->validate($request, [

        // Validation des conditions requises des champs du formulaire
            'title' => 'required|string|min:10|max:500',
            'title2' => 'required|string|min:10|max:500',
            'link' => 'required|string|min:10|max:500',
            'image' => 'required|mimes:bmp,png,jpg,jpeg|max:2048'
        ]);

        $media = new Media;
        $media->title = $request->input('title');
        $media->title2 = $request->input('title2');
        $media->link = $request->input('link');
        $media->image = $request->file('image');
        $imageName = time() . $media->image->getClientOriginalName();
        $media->image->move('uploads/medias', $imageName);
        $media->image = $imageName;
        $media->user_id = Auth::user()->id;
        $media->save();

        return redirect('index#media')->with('success', 'Votre média à été crée !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function show($id){

        $media = Media::with('user')->find($id);
        return view('medias.show')->with('media', $media);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function edit($id){

        $media = Media::find($id);

    if(auth()->user()->id !== $media->user_id) {

        return redirect('/medias')->with('error', 'Non autorisé');
        }
        return view('medias.edit')->with('media', $media);
        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){

        $this->validate($request, [

        // Validation des conditions requises des champs du formulaire
            'title' => 'required|string|min:10|max:500',
            'title2' => 'required|string|min:10|max:500',
            'link' => 'required|string|min:10|max:500',
            'image' => 'required|mimes:bmp,png,jpg,jpeg|max:2048'
        ]);

        $media = Media::find($id);
        $media->title = $request->input('title');
        $media->title2 = $request->input('title2');
        $media->link = $request->input('link');
        $media->image = $request->file('image');
        $imageName = time() . $media->image->getClientOriginalName();
        $media->image->move('uploads/medias', $imageName);
        $media->image = $imageName;
        $media->user_id = Auth::user()->id;
        $media->save();

        return redirect('/index#media')->with('success', 'Votre média à été modifié !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Media  $media
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {

        $media = Media::find($id);

        if(auth()->user()->id !== $media->user_id) {
            return redirect('/index#media')->with('error', 'Non autorisé');
        }

        $media->delete();

        return redirect('/index#media')->with('success', 'Votre média à bien été supprimé !');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/medias/create.blade.php
<x-app-layout>
    <div class="tm-main">
        <div class="tm-section-wrap">
            <div class="tm-parallax" data-parallax="scroll" data-image-src="{{ asset('img/slide4.jpg') }}">
            </div>
            <section id="home" class="tm-section">
                <h2 class="tm-text-primary">Création d'un média</h2>
                <hr class="mb-5">
                <form method="POST" action="{{ route('medias.store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="mt-4">
                        <x-jet-label for="title" value="{{ __('Titre') }}" />
                        <x-jet-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')"
                            placeholder="Titre" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="title2" value="{{ __('Titre2') }}" />
                        <x-jet-input id="title2" class="block mt-1 w-full" type="text" name="title2" :value="old('title2')"
                            placeholder="Titre2" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="link" value="{{ __('Lien') }}" />
                        <x-jet-input id="link" class="block mt-1 w-full" type="text" name="link" :value="old('link')"
                            placeholder="Lien" required />
                    </div>

                    <div class="mt-4">
                        <div class="custom-file">
                            <label for="validatedCustomFile" class="custom-file-label">Choisir une image</label>

                            <input type="file" class="custom-file-input @error('message') is-invalid @enderror"
                                name="image" id="validatedCustomFile">
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <a class="underline text-sm text-gray-600 hover:text-gray-900" href="/index">
                            {{ __('Annuler') }}
                        </a>

                        <x-jet-button class="ml-4">
                            {{ __('Poster') }}
                        </x-jet-button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
</x-app-layout>

resources/views/medias/edit.blade.php
<x-app-layout>
    <div class="tm-main">
        <div class="tm-section-wrap">
            <div class="tm-parallax" data-parallax="scroll" data-image-src="{{ asset('img/slide4.jpg') }}">
            </div>
            <section id="home" class="tm-section">
                <h2 class="tm-text-primary">Modification d'un média</h2>
                <hr class="mb-5">
                <form method="POST" action="{{ route('medias.update', $media->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mt-4">
                        <x-jet-label for="title" value="{{ __('Titre') }}" />
                        <x-jet-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')"
                            placeholder="Titre" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="title2" value="{{ __('Titre2') }}" />
                        <x-jet-input id="title2" class="block mt-1 w-full" type="text" name="title2" :value="old('title2')"
                            placeholder="Titre2" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="link" value="{{ __('Lien') }}" />
                        <x-jet-input id="link" class="block mt-1 w-full" type="text" name="link" :value="old('link')"
                            placeholder="Lien" required />
                    </div>

                    <div class="mt-4">
                        <div class="custom-file">
                            <label for="validatedCustomFile" class="custom-file-label">Choisir une image</label>

                            <input type="file" class="custom-file-input @error('message') is-invalid @enderror"
                                name="image" id="validatedCustomFile">
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <a class="underline text-sm text-gray-600 hover:text-gray-900" href="/index">
                            {{ __('Annuler') }}
                        </a>

                        <x-jet-button class="ml-4">
                            {{ __('Modifier') }}
                        </x-jet-button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
</x-app-layout>